blank_issues_enabled: false
contact_links:
  - name: Ask questions
    url: https://github.com/OscarNOW/minecraft/discussions/categories/questions
    about: Please ask questions here, instead of opening an issue
