name: Feature request
description: Suggest an idea for this package
labels: [feature request]
assignees:
  - OscarNOW
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing this feature request! We'll look at this as soon as possible.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem is your feature request related to? Please provide a clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution to problem
      description: Describe the solution you'd like. Please provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternative_solutions
    attributes:
      label: Alternative solutions
      description: Describe alternatives you've considered.
    validations:
      required: false

  - type: textarea
    id: additional_information
    attributes:
      label: Additional information
      description: If you have any additional information like screenshots, please provide it here.
    validations:
      required: false
