const fs = require('fs');
const path = require('path');

let readme = fs.readFileSync(path.join(__dirname, '../.github/README.md')).toString();

readme = readme.split('\n');
readme = readme.filter(a => !a.includes('#gh-dark-mode-only'));
readme = readme.join('\n');

readme = '<!-- This file is copied from ./github/README.md . Do not edit this file directly, instead edit ./github/README.md -->\n\n' + readme;

fs.writeFileSync(path.join(__dirname, '../README.md'), readme)