name: Check build

on: [push, pull_request]

jobs:
  check-build:
    runs-on: ubuntu-latest
    name: Check build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Check build
        run: node src/checkBuild
