name: Docs

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Docs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build-types
        run: npm run types
      - name: Build-docs
        run: npm run docs
      - name: Push docs
        uses: EndBug/add-and-commit@v9.1.0
        with:
          add: docs --force
          author_name: ${{ github.event.head_commit.author.name }}
          author_email: ${{ github.event.head_commit.author.email }}
          message: Automatic docs
