name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build

      - name: Copy docs
        run: |
          mkdir -p "./docs/${{ github.event.inputs.version }}/"
          cp -r ./docs/github/. ./docs/${{ github.event.inputs.version }}/
      - name: Update version files
        run: node ./scripts/updateVersionFiles ${{ github.event.inputs.version }}

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Release ${{ github.event.inputs.version }}"
          branch: main

          commit_user_name: Doc-bot
          commit_user_email: actions@github.com
          commit_author: Doc-bot <actions@github.com>

      # - name: Github Release
      #   uses: ncipollo/release-action@v1.11.1
      #   with:
      #     bodyFile: CHANGELOG.md
      #     commit: main

      #     name: ${{ github.event.inputs.version }}
      #     tag: ${{ github.event.inputs.version }}

      # - name: NPM Release
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     access: public
      #     check-version: true

      #     tag: latest
