name: Test buildable

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened]

permissions: {}

jobs:
  test-buildable:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Test buildable

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check if changed
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed
        with:
          paths: . :^**.txt :^**.xlsx :^**.yml .github/workflows/test-buildable-light.yml

      - name: Install Dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: npm i

      - name: Build
        run: npm run build
