name: Test buildable

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]

permissions: {}

jobs:
  test-buildable:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Test buildable

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check if changed
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed
        with:
          paths: . :^**.txt :^**.xlsx :^**.yml .github/workflows/test-buildable-light.yml

      - name: Use Node 20.x
        if: steps.changed.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
      - name: Install Dependencies
        if: steps.changed.outputs.changed == 'true'
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: npm ci

      - name: Build
        if: steps.changed.outputs.changed == 'true'
        run: npm run build
