name: Test

on:
  workflow_dispatch:
  pull_request:

permissions: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          - node-version: 20.x
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    name: Node ${{ matrix.node-version }}, ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node ${{ matrix.node-version }}
        if: steps.changed.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install Dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: npm i
      - name: Test
        run: node scripts/test --github-action
