name: Test buildable

on:
  push:
    paths-ignore:
      - "**.txt"
      - "**.md"
      - "**.xlsx"
  pull_request:
    paths-ignore:
      - "**.txt"
      - "**.md"
      - "**.xlsx"

jobs:
  test-buildable:
    runs-on: ubuntu-latest
    name: Test buildable

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build-readme
        run: npm run readme
      - name: Build-minify
        run: npm run minify
      - name: Build-types
        run: npm run types
      - name: Build-docs
        run: npm run docs
