name: Test buildable light

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]

permissions: {}

jobs:
  test-buildable-light:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Test buildable light

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check if changed
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed
        with:
          paths: . :!**.txt :!**.xlsx :!**.yml .github/workflows/test-buildable-light.yml

      - name: Use Node 18.x
        if: steps.changed.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Install Dependencies
        if: steps.changed.outputs.changed == 'true'
        run: npm ci

      - name: Build
        if: steps.changed.outputs.changed == 'true'
        run: npm run build
