name: Test build

on: [push, pull_request]

jobs:
  test-build:
    runs-on: ubuntu-latest
    name: Test build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build-minify
        run: npm run minify
      - name: Build-types
        run: npm run types
      - name: Build-docs
        run: npm run docs
