name: Test light

on:
  workflow_dispatch:
  push:
    paths:
      - "**.*"
      - "!**.txt"
      - "!**.md"
      - "!**.xlsx"
      - "!**.d.ts"

permissions: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    name: Node ${{ matrix.node-version }}, ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: node scripts/test --github-action
