name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # node-version: [14.x, 18.x]
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [18.x]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node-version }}, ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: debug-dir
        run: dir
      - name: debug-dir-src
        run: cd src && dir
      - name: Test
        run: node src/test --github-action
