name: Test light

on:
  workflow_dispatch:
  push:

permissions: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    name: Node ${{ matrix.node-version }}, ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check if changed
        uses: MarceloPrado/has-changed-path@v1.0
        id: changed
        with:
          paths: . :^**.txt :^**.md :^**.xlsx :^**.d.ts :^**.yml .github/workflows/test-light.yml

      - name: Use Node ${{ matrix.node-version }}
        if: steps.changed.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install Dependencies
        if: steps.changed.outputs.changed == 'true'
        run: npm ci
      - name: Test
        if: steps.changed.outputs.changed == 'true'
        run: node scripts/test --github-action
